name: Push commit
on: 
  push:
    paths:
      - "**.txt"
      
permissions:
  contents: write
  
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Python
        run: python -c "import dateutil; import datetime; print(datetime.datetime.now()); print(dateutil.easter.easter(2025))" > date.txt
      - name: Commit Generated File
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "[bot] Generate new date"
          git push
